#!/bin/bash

# Update systeem
echo "Systeem updaten..."
sudo apt-get update -y

# Installeer Python 3 en pip
echo "Python en pip installeren..."
sudo apt-get install -y python3 python3-pip

# Upgrade pip
echo "pip upgraden..."
pip3 install --upgrade pip

# Installeer Jupyter Notebook
echo "Jupyter Notebook installeren..."
pip3 install --upgrade jupyter

# Installeer data science bibliotheken
echo "Data science bibliotheken installeren..."
pip3 install numpy pandas matplotlib seaborn scipy scikit-learn tensorflow keras xgboost

echo "Data science omgeving is succesvol geïnstalleerd!"
